name: AI Code Reviewer

on:
  pull_request:
    branches:
      - main

    types:
      - opened
      - synchronize

permissions:
  contents: read
  pull-requests: write
        
jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: AI Code Reviewer
        uses: kodif-team/ai-codereviewer@v3.4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_MODEL: "gpt-4.1"
          EXCLUDE: "**/*.json, **/*.md"
